### PR TITLE
Add support for building build with specific revision or tag

### PR DESCRIPTION
**Pull request by vaijab**
Related issue: #26

### CODE REVIEW

**Review by asmckinlay — APPROVED** [review]
I was just looking for this! 👍

**Comment by vaijab** [comment]
@jszwedko friendly ping. :-)

**Comment by jszwedko** [comment]
Hi @vaijab,

Apologies for the delay in review. Thanks for submitting this! I'd love to integrate this, but, as you anticipated in #26, I'm wondering if there is a way we can do this without introducing a breaking change to the API.

Adding additional methods is definitely one way, but may lead to a proliferation of methods if CircleCI adds additional parameters to the API. This reminded me of [a blog post about functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis). I'm curious if we could do something like that here to come up with an extensible API while maintaining compatibility. I was initially going to suggest creating a `BuildOptions` struct and using variadic parameters, but that post points out some of the downsides.

I'll think about this a bit more, but am open to thoughts!

**Comment by vaijab** [comment]
> This reminded me of a blog post about functional options. I'm curious if we could do something like that here to come up with an extensible API while maintaining compatibility.

I like that and I totally agree. I needed this to work, hence the PR, however I am happy to give functional options a shot. Let me know if you have other ideas in the mean time.

**Pull request closed without merging**
